import exceptions


if __name__ == "__main__":
    print(__name__)
    exceptions.divide_func(0)
